# -*- coding: utf-8 -*-
"""Copy of Hand Written Digit Recognition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j9CZll8nzRqBmwBirmUasOsh52EuHTwy
"""

import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

mnist = tf.keras.datasets.mnist

(x_train, y_train),(x_test, y_test) = mnist.load_data()

print(x_train.shape, y_train.shape, x_test.shape, y_test.shape)

plt.figure(figsize=(8,8))
for i in range(9):
  plt.subplot(3,3,i+1)
  plt.imshow(x_train[i])
  plt.title(y_train[i])
  plt.axis('off')

x_train = tf.keras.utils.normalize(x_train, axis =0)
x_test = tf.keras.utils.normalize(x_test, axis =0)

"""Building Model"""

model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Flatten(input_shape = (28,28)))
model.add(tf.keras.layers.Dense(128, activation = 'relu'))
model.add(tf.keras.layers.Dense(64, activation = 'relu'))
model.add(tf.keras.layers.Dense(32, activation = 'relu'))
model.add(tf.keras.layers.Dense(10, activation='softmax'))

model.summary()

model.compile(optimizer = 'adam', loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True), metrics =['accuracy'])

model.fit(x_train, y_train, validation_data=(x_test, y_test), batch_size=32, epochs = 15)

import cv2

image = cv2.imread('3.png')[:,:,0]
image = np.invert(np.array([image]))

output = model.predict(image)
plt.imshow(image[0])
print(np.argmax(output))

model.save('/content/hand_written_Digit_recog_model.keras')

!pip install streamlit

!streamlit run /content/app.py &> /content/logs.txt &

!npx localtunnel --port 8501

